program: mixed_precision_quant.py
method: grid
metric:
  name: average_bit_width
  goal: minimize
parameters:
  model_name:
    values:
      - "HuggingFaceTB/SmolLM-135M-Instruct"
      - "meta-llama/Llama-3.2-3B-Instruct"
      - "meta-llama/Llama-3.1-8B-Instruct"
  error_threshold:
    values: [10, 12, 15, 20]
  quantile_range:
    values:
      - [0.1, 0.9]
      - [0.05, 0.95]
      - [0.01, 0.99]
