program: quantizing_large_components.py
method: grid
project: "baa"
entity: "kaj-rauch"
metric:
  name: quantized_model_accuracy
  goal: maximize
parameters:
  model_name:
    values:
      - "HuggingFaceTB/SmolLM-135M-Instruct"
      # - "meta-llama/Llama-3.2-3B-Instruct"
      # - "meta-llama/Llama-3.1-8B-Instruct"
  weight_bits:
    # values: [2, 3, 4, 5, 6, 8]
    values: [4, 5]
  include_component:
    values:
      - "Full_Model"
      - "Self_Attention"
      # - "MLP"
      # - "LM_Head"